name: Claude Code

on:
  issues:
    types: [assigned]

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Validate issue body
        id: validate
        run: |
          export PROMPT=$(node ./scripts/gh/generate-prompt.js "${{ github.event.issue.body }}")
          if [[ -z "${{ env.PROMPT }}" ]]; then
            echo "Error: Prompt is empty"
            exit 1
          fi
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          prompt: |
            - The assigned issue contains a JSON body with inputs for instructions.md
            - Get url as URL and category as CATEGORY values for substitution into prompt below:
            - "${{ env.PROMPT }}"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      - name: Create PR from Claude response
        
        id: pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH_NAME="recipe-${{ github.event.issue.number }}"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "${BRANCH_NAME}"
          git add -A
          git commit -m "${{ github.event.issue.number }} recipe suggestion" || echo "No changes to commit"
          git push --set-upstream origin "${BRANCH_NAME}"
          gh pr create --head "${BRANCH_NAME}" --base main --title "${{ github.event.issue.number }} recipe suggestion" --body "New Recipe processed by Claude"
      - name: Upload artifacts even if Build failed
        if: ${{ always() }}              # runs on success or failure (not if job is cancelled)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            output/**
            suggestions/**
          if-no-files-found: ignore
          retention-days: 7
