name: Generate Recipe

on:
  issues:
    types: [assigned]

jobs:
  claude:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/${{ github.repository }}/ubuntu:22.04
      options: --platform=linux/amd64
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
      issues: read
      packages: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Move source files to workspace
        run: |
          echo "Moving source files to preserve /workspace dependencies"
          # Copy all repo files to /workspace, preserving existing node_modules
          cp -r * /workspace/
          cd /workspace
          echo "Contents of /workspace after copy:"
          ls -la

      - name: Parse issue inputs and fetch recipe
        env:
          PLAYWRIGHT_BROWSERS_PATH: /root/.cache/ms-playwright
        id: fetch
        run: |
          cd /workspace

          # Write issue body to file with proper escaping
          cat > /tmp/issue.json << 'EOF'
          ${{ github.event.issue.body }}
          EOF

          echo "Issue body written to /tmp/issue.json"
          cat /tmp/issue.json

          # Debug Chrome setup

          # Use the containerized recipe fetcher (don't exit on error yet)
          echo "Starting recipe fetch..."
          if CATEGORY="$(node ./scripts/run-fetch.js 2>&1)"; then
            echo "Recipe fetch completed with category: $CATEGORY"
          else
            echo "Recipe fetch failed with error:"
            echo "$CATEGORY"
            echo "Retrying with debugging..."
            node ./scripts/run-fetch.js || exit 1
          fi

          echo "CATEGORY=${CATEGORY:-entrees}" >> $GITHUB_OUTPUT

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          working_directory: /workspace
          prompt: |
            Use the @scripts/instructions.md file and the category: ${{ steps.fetch.outputs.CATEGORY }} input to complete the task
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

      - name: Create PR from Claude response
        id: pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH_NAME="recipe-${{ github.event.issue.number }}"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "${BRANCH_NAME}"
          git add -A
          git commit -m "${{ github.event.issue.number }} recipe suggestion" || echo "No changes to commit"
          git push --set-upstream origin "${BRANCH_NAME}"
          gh pr create --head "${BRANCH_NAME}" --base main --title "${{ github.event.issue.number }} recipe suggestion" --body "New Recipe processed by Claude"

      - name: Upload artifacts even if Build failed
        if: ${{ always() }}              # runs on success or failure (not if job is cancelled)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./output/**
            ./suggestions/**
          if-no-files-found: ignore
          retention-days: 7
