name: Claude Code

on:
  issues:
    types: [assigned]

jobs:
  claude:
    runs-on: ubuntu-24.04
    container: 
      image: ghcr.io/${{ github.repository }}/node:22-alpine
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
      issues: read
      packages: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Move source files to workspace
        run: |
          echo "Moving source files to preserve /workspace dependencies"
          # Copy all repo files to /workspace, preserving existing node_modules
          cp -r * /workspace/
          cd /workspace
          echo "Contents of /workspace after copy:"
          ls -la

      - name: Parse issue inputs and fetch recipe
        id: fetch
        run: |
          cd /workspace
          # Extract URL and category from issue body
          URL=$(echo '${{ github.event.issue.body }}' | jq -r '.url // empty')
          CATEGORY=$(echo '${{ github.event.issue.body }}' | jq -r '.category // empty')
          
          if [[ -z "$URL" ]]; then
            echo "Error: No URL found in issue"
            exit 1
          fi

          echo "{{ github.event.issue.body }}" > /tmp/issue.json

          # Use the containerized recipe fetcher
          node ./scripts/recipe-fetch.js "$URL"

          # Verify the output file was created
          if [[ ! -f "/tmp/html.json" ]]; then
            echo "Error: html.json was not created"
            exit 1
          fi

          # Verify the output file was created
          if [[ -f "/tmp/jsonld.json" ]]; then
            echo "Info: /tmp/jsonld.json will be used"
          else
            echo "Warn: /tmp/jsonld.json was not created"
          fi

          echo "URL=$URL" >> $GITHUB_OUTPUT
          echo "CATEGORY=${CATEGORY:-main}" >> $GITHUB_OUTPUT

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          working_directory: /workspace
          prompt: |
            Use the @scripts/instructions.md file and the category: ${{ steps.fetch.outputs.CATEGORY }} input to complete the task
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

      - name: Copy changes back to git repo
        run: |
          echo "Copying generated files back to git working directory"
          # Copy generated files from /workspace back to the git checkout directory
          cp -r /workspace/packages/app/output/* ./packages/app/output/ 2>/dev/null || echo "No output files to copy"
          cp -r /workspace/packages/app/suggestions/* ./packages/app/suggestions/ 2>/dev/null || echo "No suggestion files to copy"
          echo "Files copied back to git directory"

      - name: Create PR from Claude response
        id: pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH_NAME="recipe-${{ github.event.issue.number }}"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "${BRANCH_NAME}"
          git add -A
          git commit -m "${{ github.event.issue.number }} recipe suggestion" || echo "No changes to commit"
          git push --set-upstream origin "${BRANCH_NAME}"
          gh pr create --head "${BRANCH_NAME}" --base main --title "${{ github.event.issue.number }} recipe suggestion" --body "New Recipe processed by Claude"

      # - name: Upload artifacts even if Build failed
      #   if: ${{ always() }}              # runs on success or failure (not if job is cancelled)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifacts
      #     path: |
      #       ./output/**
      #       ./suggestions/**
      #     if-no-files-found: ignore
      #     retention-days: 7
