name: Issue Closed Handler

on:
  issues:
    types: [closed, opened]

jobs:
  handle-closed-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo Issue Information
        run: |
          echo $GITHUB_EVENT_NAME
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT