name: Issue Closed Handler

on:
  issues:
    types: [closed]

jobs:
  handle-closed-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo Issue Information
        run: echo ${{ toJson(github) }}